# Generated by Django 5.2.5 on 2025-09-06 16:14

from typing import ClassVar

from django.db import migrations


def create_user_roles(apps: object, _schema_editor: object) -> None:
    """Create user role groups for RBAC system"""
    Group = apps.get_model("auth", "Group")

    # Create role groups if they don't exist
    roles = ["admin", "instructor", "student"]
    for role in roles:
        Group.objects.get_or_create(name=role)


def remove_user_roles(apps: object, _schema_editor: object) -> None:
    """Remove user role groups"""
    Group = apps.get_model("auth", "Group")
    Group.objects.filter(name__in=["admin", "instructor", "student"]).delete()


class Migration(migrations.Migration):
    dependencies: ClassVar[list] = []

    operations: ClassVar[list] = [
        migrations.RunPython(create_user_roles, remove_user_roles),
    ]
