# Generated by Django 5.2.5 on 2025-09-09 05:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("patients", "0002_alter_file_options"),
        ("student_groups", "0002_labrequest"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BloodSugar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sugar_level",
                    models.DecimalField(
                        decimal_places=1,
                        max_digits=5,
                        verbose_name="Blood Sugar Level (mg/dL)",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blood_sugars",
                        to="patients.patient",
                        verbose_name="Patient",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blood_sugars",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Blood Sugar",
                "verbose_name_plural": "Blood Sugars",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OxygenSaturation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "saturation_percentage",
                    models.PositiveIntegerField(verbose_name="Oxygen Saturation (%)"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="oxygen_saturations",
                        to="patients.patient",
                        verbose_name="Patient",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="oxygen_saturations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Oxygen Saturation",
                "verbose_name_plural": "Oxygen Saturations",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RespiratoryRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "respiratory_rate",
                    models.PositiveIntegerField(
                        verbose_name="Respiratory Rate (breaths/min)"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="respiratory_rates",
                        to="patients.patient",
                        verbose_name="Patient",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="respiratory_rates",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Respiratory Rate",
                "verbose_name_plural": "Respiratory Rates",
                "ordering": ["-created_at"],
            },
        ),
    ]
