# Generated by Django 5.2.5 on 2025-09-09 06:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("student_groups", "0003_add_new_observation_models"),
    ]

    operations = [
        migrations.AddField(
            model_name="labrequest",
            name="reason",
            field=models.TextField(default="", verbose_name="Reason"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="note",
            name="name",
            field=models.CharField(
                default="", max_length=100, verbose_name="Doctor Name"
            ),
            preserve_default=False,
        ),
    ]
