# Generated by Django 5.2.5 on 2025-09-09 12:10

from typing import Any, ClassVar

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies: ClassVar[list[Any]] = [
        ("patients", "0003_file_requires_pagination"),
        ("student_groups", "0004_labrequest_reason_note_name"),
    ]

    operations: ClassVar[list[Any]] = [
        migrations.AlterField(
            model_name="labrequest",
            name="reason",
            field=models.TextField(verbose_name="Reason for Request"),
        ),
        migrations.AlterField(
            model_name="labrequest",
            name="status",
            field=models.CharField(
                choices=[("pending", "Pending"), ("completed", "Completed")],
                default="pending",
                max_length=10,
                verbose_name="Status",
            ),
        ),
        migrations.CreateModel(
            name="ApprovedFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "page_range",
                    models.CharField(
                        blank=True,
                        help_text="e.g., '1-5', '7', '10-12'. Only for paginated files.",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="patients.file",
                    ),
                ),
                (
                    "lab_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="student_groups.labrequest",
                    ),
                ),
            ],
            options={
                "verbose_name": "Approved File",
                "verbose_name_plural": "Approved Files",
                "unique_together": {("lab_request", "file")},
            },
        ),
        migrations.AddField(
            model_name="labrequest",
            name="approved_files",
            field=models.ManyToManyField(
                related_name="lab_requests",
                through="student_groups.ApprovedFile",
                to="patients.file",
                verbose_name="Approved Files",
            ),
        ),
    ]
