# Generated by Django 5.2.5 on 2025-09-24 15:45

from typing import Any, ClassVar

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies: ClassVar[list[Any]] = [
        ("patients", "0004_file_category"),
        ("student_groups", "0006_painscore"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations: ClassVar[list[Any]] = [
        migrations.AddField(
            model_name="note",
            name="role",
            field=models.CharField(default="", max_length=50, verbose_name="Role"),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="BloodTestRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "test_type",
                    models.CharField(
                        choices=[
                            ("FBC", "Full Blood Count"),
                            ("EUC", "Electrolytes, Urea, Creatinine"),
                            ("LFTs", "Liver Function Tests"),
                            ("Coags", "Coagulation Profile"),
                            ("CRP", "C-Reactive Protein"),
                            ("TFT", "Thyroid Function Tests"),
                            ("Group and Hold", "Group and Hold"),
                        ],
                        max_length=50,
                        verbose_name="Test Type",
                    ),
                ),
                ("reason", models.TextField(verbose_name="Reason for Request")),
                (
                    "status",
                    models.CharField(
                        choices=[("pending", "Pending"), ("completed", "Completed")],
                        default="pending",
                        max_length=10,
                        verbose_name="Status",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Name")),
                ("role", models.CharField(max_length=50, verbose_name="Role")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "approved_files",
                    models.ManyToManyField(
                        blank=True,
                        related_name="blood_test_requests",
                        to="patients.file",
                        verbose_name="Approved Files",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blood_test_requests",
                        to="patients.patient",
                        verbose_name="Patient",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blood_test_requests",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Blood Test Request",
                "verbose_name_plural": "Blood Test Requests",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DischargeSummary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("diagnosis", models.TextField(verbose_name="Diagnosis")),
                ("plan", models.TextField(verbose_name="Plan")),
                ("free_text", models.TextField(blank=True, verbose_name="Free Text")),
                ("name", models.CharField(max_length=100, verbose_name="Name")),
                ("role", models.CharField(max_length=50, verbose_name="Role")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="discharge_summaries",
                        to="patients.patient",
                        verbose_name="Patient",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="discharge_summaries",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Discharge Summary",
                "verbose_name_plural": "Discharge Summaries",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ImagingRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "test_type",
                    models.CharField(
                        choices=[
                            ("X-ray", "X-ray"),
                            ("CT scan", "CT scan"),
                            ("MRI scan", "MRI scan"),
                            ("Ultrasound scan", "Ultrasound scan"),
                            ("Echocardiogram", "Echocardiogram"),
                        ],
                        max_length=50,
                        verbose_name="Test Type",
                    ),
                ),
                ("reason", models.TextField(verbose_name="Reason for Request")),
                (
                    "status",
                    models.CharField(
                        choices=[("pending", "Pending"), ("completed", "Completed")],
                        default="pending",
                        max_length=10,
                        verbose_name="Status",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Name")),
                ("role", models.CharField(max_length=50, verbose_name="Role")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "approved_files",
                    models.ManyToManyField(
                        related_name="imaging_requests",
                        through="student_groups.ApprovedFile",
                        to="patients.file",
                        verbose_name="Approved Files",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="imaging_requests",
                        to="patients.patient",
                        verbose_name="Patient",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="imaging_requests",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Imaging Request",
                "verbose_name_plural": "Imaging Requests",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AlterUniqueTogether(
            name="approvedfile",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="approvedfile",
            name="imaging_request",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                to="student_groups.imagingrequest",
            ),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name="approvedfile",
            unique_together={("imaging_request", "file")},
        ),
        migrations.CreateModel(
            name="MedicationOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "medication_name",
                    models.CharField(max_length=255, verbose_name="Medication Name"),
                ),
                ("dosage", models.CharField(max_length=100, verbose_name="Dosage")),
                ("instructions", models.TextField(verbose_name="Instructions")),
                ("name", models.CharField(max_length=100, verbose_name="Name")),
                ("role", models.CharField(max_length=50, verbose_name="Role")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="medication_orders",
                        to="patients.patient",
                        verbose_name="Patient",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="medication_orders",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Medication Order",
                "verbose_name_plural": "Medication Orders",
                "ordering": ["-created_at"],
            },
        ),
        migrations.RemoveField(
            model_name="approvedfile",
            name="lab_request",
        ),
        migrations.DeleteModel(
            name="LabRequest",
        ),
    ]
