# Generated by Django 5.2.5 on 2025-10-14 08:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("student_groups", "0009_refactor_request_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="approvedfile",
            name="page_range",
            field=models.CharField(
                blank=True,
                default="",
                help_text="e.g., '1-5', '7', '10-12'. Only for paginated files.",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="bloodtestrequest",
            name="test_type",
            field=models.CharField(
                choices=[
                    ("FBC", "Full Blood Count"),
                    ("EUC", "Electrolytes, Urea, Creatinine"),
                    ("LFTs", "Liver Function Tests"),
                    ("Lipase", "Lipase"),
                    ("Troponin", "Troponin"),
                    ("Coag", "Coagulation Profile"),
                    ("D-dimer", "D-dimer"),
                    ("CRP", "C-Reactive Protein"),
                    ("VBG", "Venous Blood Gas"),
                    ("Haptoglobin", "Haptoglobin"),
                    ("LDH", "Lactate Dehydrogenase"),
                    ("Group & Hold", "Group & Hold"),
                    ("Crossmatch", "Crossmatch"),
                    ("Blood Culture", "Blood Culture"),
                    ("TFT", "Thyroid Function Tests"),
                ],
                max_length=50,
                verbose_name="Test Type",
            ),
        ),
    ]
