# Generated by Django 5.2.5 on 2025-09-05 16:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("patients", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="file",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "File",
                "verbose_name_plural": "Files",
            },
        ),
    ]
