# Generated by Django 5.2.5 on 2025-09-09 12:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("patients", "0002_alter_file_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="file",
            name="requires_pagination",
            field=models.BooleanField(
                default=False,
                help_text="Only for PDF files. If true, access can be granted by page ranges.",
                verbose_name="Requires Pagination",
            ),
        ),
    ]
