# Generated by Django 5.2.5 on 2025-09-24 15:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("patients", "0003_file_requires_pagination"),
    ]

    operations = [
        migrations.AddField(
            model_name="file",
            name="category",
            field=models.CharField(
                choices=[
                    ("Admission", "Admission"),
                    ("Pathology", "Pathology"),
                    ("Imaging", "Imaging"),
                    ("Diagnostics", "Diagnostics"),
                    ("Lab Results", "Lab Results"),
                    ("Other", "Other"),
                ],
                default="Other",
                max_length=20,
                verbose_name="Category",
            ),
        ),
    ]
