# Generated by Django 5.2.5 on 2025-10-12 17:38

import uuid
from typing import Any, ClassVar

from django.db import migrations, models


def _populate_mrns(apps: object, _schema_editor: object) -> None:
    """Populate MRN values for existing Patient rows.

    This function mirrors the original migration intent but is defined at module
    level to avoid lambda nesting and to satisfy linter checks.
    """

    Patient = apps.get_model("patients", "Patient")

    for p in Patient.objects.filter(mrn__isnull=True):
        p.mrn = f"MRN-{p.pk}-{uuid.uuid4().hex[:8]}"
        p.save()


class Migration(migrations.Migration):
    dependencies: ClassVar[list[Any]] = [
        ("patients", "0004_file_category"),
    ]

    operations: ClassVar[list[Any]] = [
        migrations.AddField(
            model_name="patient",
            name="bed",
            field=models.CharField(default="", max_length=20, verbose_name="Bed"),
            preserve_default=False,
        ),
        # Add mrn as nullable first to avoid UNIQUE constraint failures when populating
        migrations.AddField(
            model_name="patient",
            name="mrn",
            field=models.CharField(
                max_length=50,
                null=True,
                blank=True,
                verbose_name="Medical Record Number (MRN)",
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="ward",
            field=models.CharField(default="", max_length=100, verbose_name="Ward"),
            preserve_default=False,
        ),
        # Populate unique MRNs for existing rows before enforcing uniqueness
        migrations.RunPython(
            code=_populate_mrns, reverse_code=migrations.RunPython.noop
        ),
        # Now alter the field to be unique and non-nullable
        migrations.AlterField(
            model_name="patient",
            name="mrn",
            field=models.CharField(
                max_length=50,
                unique=True,
                verbose_name="Medical Record Number (MRN)",
            ),
        ),
    ]
