# Generated by Django 5.2.5 on 2025-10-13 03:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("patients", "0005_add_mrn_ward_bed_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="gender",
            field=models.CharField(
                choices=[
                    ("female", "Female"),
                    ("male", "Male"),
                    ("other", "Other"),
                    ("unspecified", "Unspecified"),
                ],
                default="unspecified",
                help_text="Patient's gender",
                max_length=20,
                verbose_name="Gender",
            ),
        ),
    ]
