# Generated by Django 5.2.5 on 2025-10-14 04:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("patients", "0006_patient_gender"),
    ]

    operations = [
        migrations.CreateModel(
            name="GoogleFormLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="The title of the Google Form",
                        max_length=255,
                        verbose_name="Form Title",
                    ),
                ),
                (
                    "url",
                    models.URLField(
                        help_text="The complete URL to the Google Form",
                        max_length=500,
                        verbose_name="Form URL",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Optional description of the form's purpose",
                        verbose_name="Description",
                    ),
                ),
                (
                    "display_order",
                    models.IntegerField(
                        default=0,
                        help_text="Order in which the form appears (lower numbers first)",
                        verbose_name="Display Order",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this form link is currently active and visible",
                        verbose_name="Is Active",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
            ],
            options={
                "verbose_name": "Google Form Link",
                "verbose_name_plural": "Google Form Links",
                "ordering": ["display_order", "created_at"],
            },
        ),
    ]
