# Generated by ChatGPT - remove email field from Patient model
from typing import Any, ClassVar
from django.db import migrations


class Migration(migrations.Migration):
    dependencies: ClassVar[list[Any]] = [
        ("patients", "0007_googleformlink"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="patient",
            name="email",
        ),
    ]
